<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Brandastic.com
 *
 * @category    Brandastic
 * @package     Brandastic_Newsletter
 * @copyright   Copyright (c) 2019-2020 brandastic. All rights reserved. (http://www.brandastic.com/)
 * @license     https://www.brandastic.com/LICENSE.txt
 */

 /** @var \Magento\Framework\View\Element\Js\Components $block */
?>
<script type="text/x-magento-init">
    {
        "#newsletter-validate-detail": {
            "Brandastic_Newsletter/js/newsletter-subscription": {}
        }
    }
</script>
